name: System tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  system_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tox_target: [twisted-apidoc, cpython-summary, python-igraph-apidocs, cpython-apidocs, numpy-apidocs, git-buildpackage-apidocs, pytype-apidocs, temporalio-apidocs]

    steps:
    - uses: actions/checkout@v4

    - name: Set up CPython
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install tox
      run: |
        python -m pip install --upgrade pip tox

    - name: Log system information
      run: |
        test -r /etc/os-release && sh -c '. /etc/os-release && echo "OS: $PRETTY_NAME"'
        python --version
        python -c "print('\nENVIRONMENT VARIABLES\n=====================\n')"
        python -c "import os; [print(f'{k}={v}') for k, v in os.environ.items()]"

    - name: Generate API docs
      run: |
        tox -e ${{ matrix.tox_target }}

